"""add_vnpay_fields_to_transactions

Revision ID: 1e6d0e84918e
Revises: 8877d818afc4
Create Date: 2026-03-05 16:20:40.020430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6d0e84918e'
down_revision: Union[str, Sequence[str], None] = '8877d818afc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('vnp_transaction_no', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('vnp_response_code', sa.String(length=10), nullable=True))
    op.add_column('transactions', sa.Column('bank_code', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('pay_date', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'pay_date')
    op.drop_column('transactions', 'bank_code')
    op.drop_column('transactions', 'vnp_response_code')
    op.drop_column('transactions', 'vnp_transaction_no')
    # ### end Alembic commands ###
