"""add_tokens_and_transactions_tables

Revision ID: 8877d818afc4
Revises: fe00db8f1513
Create Date: 2026-03-05 15:38:54.368370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8877d818afc4'
down_revision: Union[str, Sequence[str], None] = 'fe00db8f1513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey'),
    sa.UniqueConstraint('user_id', name='tokens_user_id_key')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(), nullable=False),
    sa.Column('tokens_added', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('transaction_ref', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='transaction_status'), server_default=sa.text("'pending'::transaction_status"), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['token_packages.id'], name='transactions_package_id_fkey', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey'),
    sa.UniqueConstraint('transaction_ref', name='transactions_transaction_ref_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('tokens')
    # ### end Alembic commands ###
